force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Discount</label>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Max_Discount__c.field-meta.xml
<CustomField>
    <fullName>Max_Discount__c</fullName>
    <label>Max Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processor</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>Motherboard</fullName>
            </value>
            <value>
                <fullName>Video Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ItemPicklistTest.cls
@isTest
private class ItemPicklistTest {
   @isTest private static void getItemsPicklistTest() {
    
        System.Test.startTest();
            String type='processor';
            Item__c itm = new Item__c(Name='New Item');
            insert itm;
            List<Item__c> allItems = [SELECT Name, Type__c, Price__c FROM Item__c WHERE Type__c =: type];
            ItemPicklistApexController.Option optn = new ItemPicklistApexController.Option(itm.Name, JSON.serialize(itm));
            System.assertEquals(itm.Name, optn.label);
            System.assertEquals(JSON.serialize(itm), optn.value);
            ItemPicklistApexController.getItemsPicklist(type);
            System.assertEquals(allItems.size(), ItemPicklistApexController.getItemsPicklist(type).size());
        System.Test.stopTest();

    }

    @isTest private static void getMaxCustomDiscountTest(){
        System.Test.startTest();
            Profile pf= [SELECT Id FROM Profile WHERE Name='System Administrator']; 
            String orgId=UserInfo.getOrganizationId(); 
            Discount__c disc = Discount__c.getInstance(pf.Id);
            Decimal testDisc = disc.Max_Discount__c;
            Decimal maxDisc = ItemPicklistApexController.getMaxCustomDiscount();
            System.assertEquals(testDisc, maxDisc);
        System.test.stopTest();
    }
    
}