force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Discount</label>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Max_Discount__c.field-meta.xml
<CustomField>
    <fullName>Max_Discount__c</fullName>
    <label>Max Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processor</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>Motherboard</fullName>
            </value>
            <value>
                <fullName>Video Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ItemPicklistController.cls
public with sharing class ItemPicklistController {
    @AuraEnabled
    public static List<Option> getItemsPicklist(String type){

        List<Item__c> allItems = [SELECT Name, Type__c, Price__c FROM Item__c WHERE Type__c =: type];
        List<Option> itemNames = new List<Option>();
        for(Item__c item : allItems){
            itemNames.add(new Option(item.name,JSON.serialize(item)));
        }
        return itemNames;
    }

    @AuraEnabled
    public static Decimal getMaxCustomDiscount(){
        Id userId=userinfo.getUserId();
        Discount__c disc = Discount__c.getInstance(userId);
        Decimal maxDisc = disc.Max_Discount__c;
        return maxDisc;

    }
    
    public class Option{
        @AuraEnabled
        public String label;
        @AuraEnabled
        public String value;
        public Option(String label, String value){
            this.label = label;
            this.value = value;
        }
    }
}