force-app/main/default/objects/Contact/fields/First_Purchase__c.field-meta.xml
<CustomField>
    <fullName>First_Purchase__c</fullName>
    <label>First Purchase</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Last_Purchase__c</fullName>
    <label>Last Purchase</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total amount that was spent by Contact</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase__c/Purchase__c.object-meta.xml
<CustomObject>
    <label>Purchase</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Purchases</relationshipLabel>
    <relationshipName>Purchases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase__c/fields/Purchase_Date__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Purchase Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PurchaseTriggerHandler.cls
public with sharing class PurchaseTriggerHandler {
    public static void purchaseDataSetup(List<Purchase__c> purchases) {
        List<Id> contIdList = new List<Id>();
        
        for (Purchase__c newPurch : purchases){
            if(String.isNotBlank(newPurch.Contact__c)){
                contIdList.add(newPurch.Contact__c);
            }
        }
        
        Map<Id,Contact> consForUpdate = new Map<Id, Contact> ([SELECT Id, First_Purchase__c, Last_Purchase__c, Total_Amount__c FROM Contact WHERE Id IN :contIdList]);

        for (Purchase__c newPurch : purchases){
            if(newPurch.Contact__c != null){
                Contact con = consForUpdate.get(newPurch.Contact__c);

                if (con.First_Purchase__c == null && con.Last_Purchase__c == null){
                    con.First_Purchase__c = newPurch.Purchase_Date__c;
                    con.Last_Purchase__c = newPurch.Purchase_Date__c;
                } else if(newPurch.Purchase_Date__c >=con.Last_Purchase__c){
                    con.Last_Purchase__c = newPurch.Purchase_Date__c;
                } else if(newPurch.Purchase_Date__c <= con.Last_Purchase__c){
                    con.First_Purchase__c = newPurch.Purchase_Date__c;
                }

                if(con.Total_Amount__c == null){
                    con.Total_Amount__c = newPurch.Amount__c;
                } else con.Total_Amount__c += newPurch.Amount__c;
            }
            
        }
        update consForUpdate.values();

    }

}