force-app/main/default/objects/Contact/fields/Personal_Discount__c.field-meta.xml
<CustomField>
    <fullName>Personal_Discount__c</fullName>
    <label>Personal Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Discount</label>
</CustomObject>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Processor</fullName>
            </value>
            <value>
                <fullName>RAM</fullName>
            </value>
            <value>
                <fullName>Motherboard</fullName>
            </value>
            <value>
                <fullName>Video Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Item__c/Purchase_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Item</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Purchase Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Item__c/fields/DIscount__c.field-meta.xml
<CustomField>
    <fullName>DIscount__c</fullName>
    <label>DIscount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Purchase_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Purchase Items</relationshipLabel>
    <relationshipName>Purchase_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CalculationApexController.cls
public with sharing class CalculationApexController {

    @AuraEnabled
    public static List<ItemWrapper> getChosenItemsList(){
        List<ItemWrapper> chosenItemsList = new List<ItemWrapper>();
        return chosenItemsList;
    }
    public class ItemWrapper{
        @AuraEnabled
        public String itemName{get;set;}

        @AuraEnabled
        public Integer itemQuantity{get;set;}

        @AuraEnabled
        public Double itemPrice{get;set;}

        @AuraEnabled
        public Double itemDiscount{get;set;}


        // public ItemWrapper (String itemName, Integer itemQuantity, Double itemPrice, Double itemDiscount){
        //     this.itemName = itemName;
        //     this.itemQuantity=itemQuantity;
        //     this.itemPrice=itemPrice;
        //     this.itemDiscount=itemDiscount;
        // }
    }
    @AuraEnabled
    public static List<ItemWrapper> combineItemLists(List<ItemWrapper> procRows, List<ItemWrapper> ramsRows, 
    List<ItemWrapper> motherboardsRows, List<ItemWrapper> videocardsRows){
        List<ItemWrapper> fullList = new List <ItemWrapper>();
        fullList.addall(procRows);
        fullList.addall(ramsRows);
        fullList.addall(motherboardsRows);
        fullList.addall(videocardsRows);
        System.debug('hello');
        System.debug(fullList);
        return fullList;

        
    }
}

    // public static List<ItemWrapper> getChosenItemsList() {
        
        
    //     // List<Item__c> itemsList = [SELECT Id, Name, Price__c, Type__c FROM Item__c ];
    //     // List<Contact> conList = [SELECT Id, Name, Personal_Discount__c FROM Contact];
    //     // List<ItemsWrapper> lst = new List<ItemsWrapper>();
    //     // for (Item_c item : itemsList){
    //     //     lst.add(new ItemsWrapper(JSON.serialize(item),JSON.serialize()))
    //     // }
    //     // return lst;
    // }
    //     @AuraEnabled
    // public static ItemWrapper getChosenItemsList(){
    //     List<Item__c> itms = [SELECT Name, Price__c FROM Item__c];
    //     List<Purchase_Item__c> purchItms = [SELECT Quantity__c, Discount__c FROM Purchase_Item__c];
    //     ItemWrapper chosenItemsList = new ItemWrapper(Item__c.Name, Purchase_Item__c.Quantity__c, Item__c.Price__c, Purchase_Item__c.Discount__c);
    //     // chosenItemsList.itemName = itms.Name;
    //     // chosenItemsList.itemPrice = itms.Price__c;
    //     // chosenItemsList.itemQuantity = purchItms.Quantity__c;
    //     // chosenItemsList.itemDiscount = purchItms.Discount__c; 
    //     System.debug(chosenItemsList);
    //     return chosenItemsList;
    // }