force-app/main/default/objects/Contact/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total amount that was spent by Contact</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase__c/Purchase__c.object-meta.xml
<CustomObject>
    <label>Purchase</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Purchase Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Item__c/Purchase_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Item</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Purchase Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Purchase Items</relationshipLabel>
    <relationshipName>Purchase_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Item__c/fields/Purchase__c.field-meta.xml
<CustomField>
    <fullName>Purchase__c</fullName>
    <label>Purchase</label>
    <referenceTo>Purchase__c</referenceTo>
    <relationshipLabel>Purchase Items</relationshipLabel>
    <relationshipName>Purchase_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CalculationTest.cls
@IsTest 
private with sharing class CalculationTest {
    static String dateStr = Datetime.now().format('YYYY-MM-dd');
    static Decimal totalSumWithDiscount = 34567;
    static String discType = 'Automatic';
    
    @TestSetup
    static void setup(){
        Contact cont = new Contact (LastName = 'Black', Total_Amount__c = 0);
        insert cont;
        List<Item__c> itemList = new List<Item__c>();
        for (Integer i=0;i<5;i++){
            itemList.add(new Item__c(Name = 'Asus Prime '+i));
        }
        insert itemList;
    }
    static CalculationController.ItemWrapper createWrapper(){
        CalculationController.ItemWrapper itmWrapp = new CalculationController.ItemWrapper();
        itmWrapp.itemName = 'Asus Prime 1';
        itmWrapp.itemDiscount = 25;
        itmWrapp.itemPrice = 564;
        itmWrapp.itemQuantity = 3;
        return itmWrapp;
    }

    @IsTest private static void saveOrderTest(){
        Contact cont = [SELECT Id FROM Contact];
        CalculationController.ItemWrapper itmWrapp = createWrapper();
        List<CalculationController.ItemWrapper> itmList = new List<CalculationController.ItemWrapper>();
        itmList.add(itmWrapp);
        Test.startTest();
            try {
                CalculationController.saveOrderMethod(cont.Id, itmList, totalSumWithDiscount, dateStr, discType);
            } catch (Exception e) {
                System.debug('exception: '+e);
            }
        Test.stopTest();
        Integer purch = [SELECT COUNT() FROM Purchase__c];
        Integer purchItems = [SELECT COUNT() FROM Purchase_Item__c ];

        System.assertEquals(1, purch);
        System.assertEquals(1, purchItems);

    }

}